### ISSUE TITLE
Items imported from MV-inv that have color in their names have weird characters in front

### ISSUE THREAD

**Issue by elFlashor** [Gnat008/PerWorldInventory#102]
Items imported from MV-inv that have coloured text in their name or lore gets very specific character added in front of the text: Ã,Â (can be seen in the screenshot below)

![clipboard01](https://cloud.githubusercontent.com/assets/713705/18256125/7f7718e8-73b1-11e6-8a3d-7b159d19fa93.jpg)

The color seems to vary between yellow, purple, white... maybe more?

**Comment by Gnat008** [comment]
Does this still happen with that version I linked in the other issue?
