### ISSUE TITLE
Gamemode bypass perm not working

### ISSUE THREAD

**Issue by Gida4** [Gnat008/PerWorldInventory#112]
Excellent plugin, i love it. But gamemode bypass not working. Please fix it. Inventory bypass working well. PaperSpigot 1.10.2 with GroupManagerX (http://ci.xephi.fr/job/GroupManagerX/)

**Comment by Gnat008** [comment]
Could you enable debug mode in the plugin config, reproduce the issue, and send me your server log?

**Comment by Gida4** [comment]
Here is the log.
[latest.log.zip](https://github.com/Gnat008/PerWorldInventory/files/476036/latest.log.zip)

**Comment by Gida4** [comment]
Please help me solve this, because it is very confusing.

**Comment by Gnat008** [comment]
Sorry, was (and am) in the process of moving. Could you tell me what you mean by "gamemode bypass is not working?" I should have asked that in my first response.

**Comment by Gida4** [comment]
When I change the world, change the gamemode. The  perworldinventory.bypass.gamemode permission does not work. The  perworldinventory.bypass.world permission working fine. See my config.
[config.txt](https://github.com/Gnat008/PerWorldInventory/files/518096/config.txt)

**Comment by Gida4** [comment]
Please help me solve this, because it is very confusing.

**Comment by Gnat008** [comment]
What version of PWI are you using?

**Comment by Gida4** [comment]
1.8.3

**Comment by Gnat008** [comment]
Could you enable debugging in the config, reproduce the issue, and post your server log here?

**Comment by Gida4** [comment]
I've sent September 16.

**Comment by Gnat008** [comment]
Oops, so you did! It does appear that you have the bypass permission. This means that your inventory should not change when switching gamemodes. Is this not the case?

**Comment by Gida4** [comment]
Nop. I am an op. My gamemode change when I change the world. Inventory bypass working fine, gamemode bypass not working.

**Comment by Gnat008** [comment]
Your gamemode SHOULD change. Your INVENTORY should not change when your gamemode changes.

**Comment by Gida4** [comment]
Yes. The sooner poorly understood you. There is little knowledge of English.

**Comment by Gnat008** [comment]
So is that what happens? If not, can you try to describe in detail what you are seeing?

**Comment by Gida4** [comment]
When I go to the creative world from surviving world, or vice versa, my gamemode change. This is not good, because i have gamemode bypass. (Sorry my bad english)

**Comment by sloanr333** [comment]
Hey I am actually wondering about this myself. I would like to keep the gamemode inventories separate, but if an Admin/Mod on my server is in creative, and goes through a nether portal (I'm using Multiverse, so it's technically another world), it forces them back to survival and they have to /gamemode to get it back to creative every time. It would be nice if we could add a permissions like perworldinventory.bypass.forcegamemode that would only disable the setting of their game mode, but would allow them to keep the separate inventories. I hope that made sense...

**Comment by sloanr333** [comment]
Actually I've just added a pull request #132 with this very functionality. Hope that helps?

**Comment by Gida4** [comment]
I hope so. Thank you did you do with the problem.

**Comment by sloanr333** [comment]
Is this what you were looking for? Did this solve your problem?
