### ISSUE TITLE
Set up?

### ISSUE THREAD

**Issue by GrannyTsunade** [Gnat008/PerWorldInventory#113]
okay so I had help from someone to set per world inventory up (he's a know it all) and ever since then its keeping the same inventories for all the worlds I have. If i change or set it back to how it first was, it doesn't want to work I don't know if this person that helped me set it up wrong but please tell me if he did. Thanks. http://pastebin.com/yncE6LXc

**Comment by Gnat008** [comment]
It is set up wrong. :) Remove all lines starting with 'group:' except for the first, and it should be fine.

**Comment by GrannyTsunade** [comment]
So it should look like this? http://pastebin.com/vGa5kiff

**Comment by Gnat008** [comment]
Remove two spaces in front of each group name after the first. I'll try to remember to explain that more later.

**Comment by GrannyTsunade** [comment]
Sorry I never set anything like this up before I don't really understand it. http://pastebin.com/V2hqwj96

**Comment by Gnat008** [comment]
At a quick glance, that looks correct.

**Comment by GrannyTsunade** [comment]
Sweet thank you :D

**Comment by Gnat008** [comment]
@GrannyTsunade, is this issue resolved?

**Comment by GrannyTsunade** [comment]
It is, thank you

**Comment by Gnat008** [comment]
Glad everything is working!
