### ISSUE TITLE
Inventory's wont switch [High priority]

### ISSUE THREAD

**Issue by bolleboor** [Gnat008/PerWorldInventory#116]
Hello I found an issue for the switch
As you join an other world the inventory wont switch
Can you fix it?

PasteBin: [http://pastebin.com/v5iBHyRS]

Thanks,
Greetings bolleboor

**Comment by Gnat008** [comment]
I'm going to mark this as a duplicate of #115 to try to keep the discussion and stuff together.

**Comment by Gnat008** [comment]
Closing duplicate, please see Issue #115.
