### ISSUE TITLE
datadefaults ?

### ISSUE THREAD

**Issue by anemul** [Gnat008/PerWorldInventory#117]
I have been having this issue when zoning into another world on my server . I get the error in the following .png and then the other two .png's show the folders made by PWI on a clean install .
![datadefaults_error](https://cloud.githubusercontent.com/assets/16367097/18811026/e18f33ea-826a-11e6-8f63-79e357f83a6b.png)
![data](https://cloud.githubusercontent.com/assets/16367097/18811027/e6d3cf96-826a-11e6-9ccd-cb605eadeb01.png)
![defaults](https://cloud.githubusercontent.com/assets/16367097/18811028/ea8553da-826a-11e6-9e78-76acae37daab.png)

What should I do ?

**Comment by anemul** [comment]
I tried creating a folder called datadefaults and dropping those files default.json in the foler , it stops the errors , but inventory is not being saved for that world .

**Comment by Gnat008** [comment]
Should be fixed with 9d8b643. I guess with the stuff related to moving, it never got released.

**Comment by anemul** [comment]
Seems to be fixed , Thank you
