### ISSUE TITLE
"Something went horribly wrong when loading your inventory!"

### ISSUE THREAD

**Issue by kal256** [Gnat008/PerWorldInventory#118]
I'm currently running a 1.10.2 server, with version 1.8.2 of PWI. I'm currently having an issue where if a player hasn't been in a world before or gamemode. It'll notify them with the message "Something went horribly wrong when loading your inventory!" However, when that player has been to that world or gamemode and placed something in their inventory, it won't show it again. Is there a way of stopping this?

My logs of when this happens:

```
.09 11:55:10 [Server] ERROR [PerWorldInventory] Unable to find inventory data for player 'PLAYER' for group 'WORLD': plugins/PerWorldInventory/datadefaults/__default.json (No such file or directory)
25.09 11:55:10 [Server] ERROR [PerWorldInventory] Unable to find inventory data for player 'PLAYER' for group 'WORLD': plugins/PerWorldInventory/datadefaults/__default.json (No such file or directory)
```

**Comment by kal256** [comment]
PWI is also generating this error from time to time. `WARN Exception in thread "Craft Scheduler Thread - 19" 
25.09 22:09:13 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin PerWorldInventory v1.8.2 generated an exception while executing task 2195`

**Comment by ezrareeves** [comment]
I'm am getting this as well after updating to the latest version.

**Comment by ezrareeves** [comment]
Looking at the error it seems a "/" is missing

**Comment by Gnat008** [comment]
Should be fixed with 9d8b643. I guess with the stuff related to moving, it never got released.

**Comment by Gnat008** [comment]
@kal256 @ezrareeves Is this still an issue?

**Comment by ezrareeves** [comment]
The invalid path problem was fixed with the last update. Thank you.
