### ISSUE TITLE
After disconnecting player loses all items

### ISSUE THREAD

**Issue by JosephTheEngineer** [Gnat008/PerWorldInventory#119]
Whenever any player disconnects and reconnects the player loses all their items.
Although i'm not to sure if it's other plugins.
A temporary solution that i'm using is to teleport to a different world before logging off.

[Server Log](http://pastebin.com/XyKxtczW)
[Configuration File](http://pastebin.com/ebDL25Ja)

Image Before:
![Image Before](http://i.imgur.com/kXa3Sq7.png)
Image After:
![Image After](http://i.imgur.com/KODiWeh.png)

Plugins:
![Plugins](http://i.imgur.com/FS7oam4.png)

**Comment by JosephTheEngineer** [comment]
Don't worry guys it not to do with pwi but with other plugins as i removed all plugins except for pwi and multiverse. (How do I mark this as solved?)

**Comment by SlimeDog** [comment]
Agreed. See [https://github.com/Gnat008/PerWorldInventory/issues/162]
