### ISSUE TITLE
PerWorldInventory

### ISSUE THREAD

**Issue by Endergirl2900** [Gnat008/PerWorldInventory#125]
Hey :)

Unfortunately the plugin does not load ... : 

[08:23:54] [Server thread/ERROR]: Could not load 'plugins/perworldinventory-1.8.3.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: me/gnat008/perworldinventory/PerWorldInventory : Unsupported major.minor version 52.0
Caused by: java.lang.UnsupportedClassVersionError: me/gnat008/perworldinventory/PerWorldInventory : Unsupported major.minor version 52.0

I do not understand why.. could you pls help me??

**Comment by ljacqu** [comment]
Your server is using Java 7, PWI is using Java 8 now

**Comment by Endergirl2900** [comment]
Hey ljacqu 

thanks a lot :) it helped. Although now i got a new problem.. somehow i can't separate the worlds: 
# 'default' and 'creative' are the names of the groups
# worlds: is a list of all worlds in the group
# If you have 'manage-gamemodes' set to true in the main config, the server
# will use the 'default-gamemode' here to know what gamemode to put users in.
groups:
  default:
    worlds:
    - world
    - world_nether
    - world_the_end
    - Komaru
    - Komaru_nether
    - Komaru_the_end
  atheria:
    worlds:
    - Atheria
    - AFM
    - AFM_nether
    - AFM_the_end
    default-gamemode: SURVIVAL
  Spawn:
    worlds:
    - Spawn5

Have i done something wrong??

**Comment by fatkungfu** [comment]
@Endergirl2900 here try this
[http://pastebin.com/4y3cSWKa](url)

**Comment by Gnat008** [comment]
Never heard back, going to assume this is resolved. Please reopen if this is in error.
