### ISSUE TITLE
I am currently 1.10 using PWI - Nether not working

### ISSUE THREAD

**Issue by Sweetestprawn** [Gnat008/PerWorldInventory#126]
I am using Per World Inventory and have a few worlds. I am trying to connect my Nether world to the PvE world. Like the inventories but for some reason they won't connect. I put it into the config on how it was setup but it still isn't working.

Can anyone help?

[worlds.txt](https://github.com/Gnat008/PerWorldInventory/files/523173/worlds.txt)
[config.txt](https://github.com/Gnat008/PerWorldInventory/files/523174/config.txt)

**Comment by Gnat008** [comment]
Your worlds.yml is incorrect. Some of the spacings are wrong, and the 'worlds:' key is missing for the last two groups. Take a careful look at the example. :)

**Comment by Gnat008** [comment]
Never heard back, going to assume this is resolved. Please reopen if this is in error.
