### ISSUE TITLE
We are using Pwi

### ISSUE THREAD

**Issue by AlluTheVallu** [Gnat008/PerWorldInventory#127]
So We are running spigot 1.10.2 and We have perworldinventory.
 but when players are switching worlds their inventories gets cleared i mean if u have been mining in survival and found a lot of stuff and then the player decides to go to the creative world but when he returns to the normal world all of his items are gone all survival stuff.
and same thing when he goes to the nether he loses all of his items.
Our configurations are just fine. Here is our plugins atm 
![2016-10-18_14 27 45](https://cloud.githubusercontent.com/assets/22910871/19475931/39a3f836-953f-11e6-8bb6-e017bfbfa5ea.png)

**Comment by Gnat008** [comment]
Are there any errors in your console or server log?

**Comment by AlluTheVallu** [comment]
No there is not. :/

**Comment by Gnat008** [comment]
Step 2: Could you please show me your worlds.yml, and enable debugging in the plugin config. After enabling this, reproduce the issue and send me the server log.

**Comment by AlluTheVallu** [comment]
Thx for the help we figured out what was going on our conf file was out of date
