### ISSUE TITLE
Gamemode usebug

### ISSUE THREAD

**Issue by dartasen** [Gnat008/PerWorldInventory#131]
There is a big problem, when you die in creative mode (/kill, /suicide, fell out of the world...) you stay in creative mode when you respawn in another world.
I noticed that the player returns in survival mode when he died and returns back to creative when he clicks to respawn.
It doesn't affect OP.

looking forward to hearing from you :100:

**Comment by Gnat008** [comment]
Could you disable bypassing in the config and see if anything changes? I am unsure if this is a PWI issue or not, since death isn't covered, only world/gamemode changes.

**Comment by Gnat008** [comment]
@dartasen
