### ISSUE TITLE
Double blances

### ISSUE THREAD

**Issue by MythTheWolf** [Gnat008/PerWorldInventory#148]
There seems to be one weird bug. If you move to another world, disconnect, reconnect and move back to the first world, your balance doubles. 

No stack traces, latest spigot & latest vault.

**Comment by sloanr333** [comment]
@Gnat008 /data/players/PWIPlayerManager.java lines 282-286 maybe? if one of the withdraws doesn't work but both deposits do...

**Comment by MythTheWolf** [comment]
@sloanr333 Imma go check it out and make a pull request

**Comment by Gnat008** [comment]
@MythTheWolf Could you see if this version helps? https://drive.google.com/open?id=0B7hS84xeTkpsdkhyMFpwYm9kTVk
At the very least, it should tell us why the withdraw is failing.

**Comment by MythTheWolf** [comment]
@Gnat008 Will do.

**Comment by sloanr333** [comment]
I think he was hoping some of the output in the console would illuminate the issue. Can you run tests some more and post some of the console output around when items go missing?

**Comment by MythTheWolf** [comment]
@sloanr333 No outputs, nothing.

**Comment by MythTheWolf** [comment]
@sloanr333 I'll run more tests and send the logfile, just incase I am missing something

**Comment by MythTheWolf** [comment]
[latest.txt](https://github.com/Gnat008/PerWorldInventory/files/650562/latest.txt)

Latest log above, **_lines with ############## were inserted by me using TextEdit, not by a plugin_**

**Comment by Gnat008** [comment]
I'm now suspecting another plugin interfering with the economy. That log shows that setting the balance to 0 is definitely working. I just went through all of the possible code paths and there is only one time where anything gets added to the balance. Could you list all of your plugins for me?

**Comment by Gnat008** [comment]
Nevermind about the plugin list, I can see it in the logs. Heh.

**Comment by Gnat008** [comment]
@MythTheWolf I'm seeing on (one of) the iConomy pages that it has multiworld support... Is there anything in the config where that can be changed? Or considering that is an actual enconomy plugin, use that for multiworld economy and disable the econ function of PWI.

At the very least, see if I'm correct.

**Comment by MythTheWolf** [comment]
@Gnat008 I don't think there is, but I should have checked in the first place. I'll look through it. My bad.

**Comment by sloanr333** [comment]
@MythTheWolf Hey so can you post your pwi config and world files as well?

**Comment by MythTheWolf** [comment]
@sloanr333 Sure thing!
[Da stuff.zip](https://github.com/Gnat008/PerWorldInventory/files/655662/Da.stuff.zip)

**Comment by MythTheWolf** [comment]
For all who need a workaround pronto, [this](https://www.spigotmc.org/resources/multi-world-money.6231/) should work. Just be sure to set: 
```yml 
economy: false 
```

**Comment by SaitDev** [comment]
Currently i need to use 2 plugin to handle multi inventory then multi money, when this great plugin can do both of them. But since we still have double balance bug, i cant save my resources :/
 
I try looking up my data json, there're 2  economy variables: `bank-balance` and `balance` with always same value. So maybe when i tp back to a world my money double cauz it sums those 2 var??

My economy is iConomy7.

**Comment by Gnat008** [comment]
If that's the case, iConomy is doing it wrong if it's implementing Vault. I'll make a build that doesn't use Vault's bank balance and see if that fixes it.

**Comment by Gnat008** [comment]
Update has been released on Spigot.

**Comment by SaitDev** [comment]
I'll try it
