### ISSUE TITLE
ERROR] Could not pass event EntityPortalEvent to PerWorldInventory v1.9.0

### ISSUE THREAD

**Issue by Aalwein** [Gnat008/PerWorldInventory#152]
Occurring on Spigot 1.11

This error throws when an item is thrown through a portal. This happens when thrown through a MultiVerse portal, CreativeGates portal, or just a plain old nether portal.

8:42:10 PM [ERROR] Could not pass event EntityPortalEvent to PerWorldInventory v1.9.0
8:42:10 PM org.bukkit.event.EventException
8:42:10 PM at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.jar:git-Spigot-f950f8e-c6d6844]
8:42:10 PM at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.jar:git-Spigot-f950f8e-c6d6844]
8:42:10 PM at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.jar:git-Spigot-f950f8e-c6d6844]
8:42:10 PM at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.jar:git-Spigot-f950f8e-c6d6844]
8:42:10 PM at net.minecraft.server.v1_11_R1.Entity.c(Entity.java:2174) [spigot-1.11.jar:git-Spigot-f950f8e-c6d6844]
8:42:10 PM at net.minecraft.server.v1_11_R1.EntityItem.c(EntityItem.java:390) [spigot-1.11.jar:git-Spigot-f950f8e-c6d6844]
8:42:10 PM at net.minecraft.server.v1_11_R1.Entity.U(Entity.java:347) [spigot-1.11.jar:git-Spigot-f950f8e-c6d6844]
8:42:10 PM at net.minecraft.server.v1_11_R1.Entity.A_(Entity.java:308) [spigot-1.11.jar:git-Spigot-f950f8e-c6d6844]
8:42:10 PM at net.minecraft.server.v1_11_R1.EntityItem.A_(EntityItem.java:58) [spigot-1.11.jar:git-Spigot-f950f8e-c6d6844]
8:42:10 PM at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1652) [spigot-1.11.jar:git-Spigot-f950f8e-c6d6844]
8:42:10 PM at net.minecraft.server.v1_11_R1.World.g(World.java:1627) [spigot-1.11.jar:git-Spigot-f950f8e-c6d6844]
8:42:10 PM at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1453) [spigot-1.11.jar:git-Spigot-f950f8e-c6d6844]
8:42:10 PM at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:617) [spigot-1.11.jar:git-Spigot-f950f8e-c6d6844]
8:42:10 PM at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:806) [spigot-1.11.jar:git-Spigot-f950f8e-c6d6844]
8:42:10 PM at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-f950f8e-c6d6844]
8:42:10 PM at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-f950f8e-c6d6844]
8:42:10 PM at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-f950f8e-c6d6844]
8:42:10 PM at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
8:42:10 PM Caused by: java.lang.NullPointerException
8:42:10 PM at me.gnat008.perworldinventory.listeners.entity.EntityPortalEventListener.onEntityPortalTeleport(EntityPortalEventListener.java:35) ~[?:?]
8:42:10 PM at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
8:42:10 PM at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
8:42:10 PM at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
8:42:10 PM at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
8:42:10 PM at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.jar:git-Spigot-f950f8e-c6d6844]
8:42:10 PM ... 17 more

**Comment by Gnat008** [comment]
For some reason I'm thinking that this is because the world isn't being set in the event properly, which I cannot control. I'll do some testing to verify this, and as a workaround likely just check if the world is null.

**Comment by Aalwein** [comment]
It is probably something to do with Multiverse and its control over the nether portals, but I figured I'd post it to see if you could think of a work around. I only noticed it because the iron farm I setup is spitting a poppy through the portal every 10 seconds for the purpose of the iron farm, and the poppies were just pooling up behind the portal (so going through the plane but not teleporting to the nether).
