### ISSUE TITLE
PerWorldInventory 1.9.1 errors

### ISSUE THREAD

**Issue by Sikatsu** [Gnat008/PerWorldInventory#171]
Hey, since I updated to 1.9.1, errors appear. Also players their inventory get reset often.

Using the latest versio, freshly compiled spigot version. Latest commit being about SQLite update.

http://pastebin.com/vYM0j8DX
http://pastebin.com/tJfXmW3r

**Comment by Gnat008** [comment]
Could you show me your worlds.yml file?

**Comment by Sikatsu** [comment]
# In this file you define your groups and the worlds in them.
# Follow this format:
# groups:
#   default:
#     worlds:
#     - world
#     - world_nether
#     - world_the_end
#     default-gamemode: SURVIVAL
#   creative:
#     worlds:
#     - creative
#     default-gamemode: CREATIVE
#
# 'default' and 'creative' are the names of the groups
# worlds: is a list of all worlds in the group
# If you have 'manage-gamemodes' set to true in the main config, the server
# will use the 'default-gamemode' here to know what gamemode to put users in.
groups:
  default:
    worlds:
    - world
    - world_nether
    - world_the_end
    default-gamemode: SURVIVAL

This file has not changed and 1.9.0 worked fine. ^^

**Comment by Gnat008** [comment]
Could you turn on debug mode in the config, and make the error happen again? Then post your log here.

**Comment by Sikatsu** [comment]
This error doesn't show up anymore actually. But I have other errors when shutting down the server and just made a new issue.

**Comment by Gnat008** [comment]
I'll close this for now, then. You can re-open this one if the error pops up again.
