### ISSUE TITLE
API Question

### ISSUE THREAD

**Issue by xtomyserrax** [Gnat008/PerWorldInventory#178]
Hi, how are you?

Im trying to hook my plugin with this one, and i would like to ask you if what i want to do is possible, and if not, if you could make it possible in the followings updates!

I have my plugin which adds the staff in a staff mode system, what is my problem? When my staff changes world, if that world is not in the same group, the inventory changes, so the staff mode items changes too. Is there a way i can make people in staff mode to avoid changing inventory in world change? (This cant be abused because when togglinf off staff mode, the staff will go back to the last location.) The staff mode inventory shouldnt be changed and saved.

Thank you for reading, if I coulnt make myself clear, please let me know!

**Comment by Gnat008** [comment]
There is a bypass permission in place; a couple, actually:

- perworldinventory.bypass.world
- perworldinventory.bypass.gamemode
- perworldinventory.bypass.enforcegamemode
- perworldinventory.bypass.*

**Comment by xtomyserrax** [comment]
Thank you then, i think i have an idea. I just will add that permission when toggle staff mode and remove it when they untoggle staff mode!

**Comment by Gnat008** [comment]
That would likely be the easiest way to do it with the route you're going.
