### ISSUE TITLE
Perworldinventory acting more like PerGamemodeInventory

### ISSUE THREAD

**Issue by suburbannoize** [Gnat008/PerWorldInventory#179]
No matter my grouping as long as I have two survival worlds their inventories are linked!
worlds.yml
groups:
default:
worlds:
- world
- world_nether
- world_the_end
- spawnin
default-gamemode: SURVIVAL
creative:
worlds:
- Creative
default-gamemode: CREATIVE
skyworld:
worlds:
- skyworld
- skyworld_nether
default-gamemode: SURVIVAL

**Comment by Gnat008** [comment]
...Can you elaborate about your issue?

**Comment by Gnat008** [comment]
Sounds like you have the bypass permission. Are you using perworldinventory.* or '*' permission nodes?

**Comment by suburbannoize** [comment]
yeah I had *,* thank you!
