### ISSUE TITLE
Perworlinventory acting more like PerGamemodeInventory

### ISSUE THREAD

**Issue by suburbannoize** [Gnat008/PerWorldInventory#180]
No matter my grouping as long as I have two survival worlds their inventories are linked!

worlds.yml

groups:
  default:
    worlds:
    - world
    - world_nether
    - world_the_end
    - spawnin
    default-gamemode: SURVIVAL
  creative:
    worlds:
    - Creative
    default-gamemode: CREATIVE
  skyworld:
    worlds:
    - skyworld
    - skyworld_nether
    default-gamemode: SURVIVAL

**Comment by suburbannoize** [comment]
????

**Comment by Gnat008** [comment]
This posted twice and neither had any details. So i left the first one open.

**Comment by Gnat008** [comment]
Duplicate, and other one resolved.
