### ISSUE TITLE
extremely inconsistent.

### ISSUE THREAD

**Issue by geb00** [Gnat008/PerWorldInventory#181]
At first the plug in seemed to work fine but eventually issues started showing up. sometimes i will go back into a world and i will get my inventory from several hours earlier, not the most recent version. Sometimes i will go into a world and get inventory that I'd never had before in that world. I think it's the same issue as #43 and #138 but neither of those have been solved. I don't get any errors in the console when switching between worlds, and I use very recent versions of both this plug in and spigot.

[pastebin.com/xMyaWzdV](http://pastebin.com/xMyaWzdV)

(note: both the worlds.yml and the config.yml are contained in the one pastebin)

**Comment by Gnat008** [comment]
Update has been released on Spigot.
