### ISSUE TITLE
Players losing inventories and error in console

### ISSUE THREAD

**Issue by meowsome** [Gnat008/PerWorldInventory#182]
Started getting this error today: https://hastebin.com/uguxejudav.vbs
And players seem to be losing their inventories at random.
My server is on 1.10.2, but it has a plugin that allows joining for any version from 1.10.2 to 1.11.2
Any way I can fix this...?

**Comment by Gnat008** [comment]
@meowsome Could you show me the PWI files from a player with this issue? ( plugins/PerWorldInventory/data/<UUID>/ )
