### ISSUE TITLE
PerWorldInventories just simply...Won't work, please help :)

### ISSUE THREAD

**Issue by MrWardy** [Gnat008/PerWorldInventory#202]
Like in the title, PWI just isn't working, it isn't separating the inventoires on my 1.11.2 spigot server.
Here's the config and worlds list.
![on8aszd](https://cloud.githubusercontent.com/assets/27183976/24845485/4d351636-1d67-11e7-8d26-bc8df5dc6dd4.png)
![t695cih](https://cloud.githubusercontent.com/assets/27183976/24845494/533790e0-1d67-11e7-981e-4984f2d9e6d7.png)

**Comment by ItsMennyo** [comment]
I see no problem?

**Comment by MrWardy** [comment]
I don't see any either, that's why I came for help

**Comment by Gnat008** [comment]
Does it not work for all players on the server, or just staff/Ops?

**Comment by MrWardy** [comment]
@Gnat008 I'm not sure, I've only tested it on myself
Is there a specific permission node to allow bypass or something?

**Comment by Gnat008** [comment]
There are:
- perworldinventory.bypass.world
- perworldinventory.bypass.gamemode
- perworldinventory.bypass.enforcegamemode

**Comment by MrWardy** [comment]
Oh wow, I'm so sorry then :P Cause I'm OP and my owner rank in PEX has the permission node '*'
So that's probably why, It should work then if I add those to negative permissions
Thank you!

**Comment by Gnat008** [comment]
Correct. Let me know if that does indeed resolve the problem!

**Comment by MrWardy** [comment]
@Gnat008 So, I'm not sure if I'm adding a negative permission right or not, but it still isn't working. Here's my permissions config for my group that I have on myself.
http://i.imgur.com/RlJhf1A.png

**Comment by im4g1n4t1onsX** [comment]
The plugin works but your config is done wrong you have to write it diffrent and convert it to multiverse with per world inventory

**Comment by MrWardy** [comment]
@Gnat008 nvm I'm just dumb, I added a negative permission wrong.

@im4g1n4t1onsX no, my PerWorldInventory's config is fine, I just added the negative permission wrong, fixed it and bam, works again. Thanks all for the support

**Comment by Gnat008** [comment]
@MrWardy So this is no longer an issue?

**Comment by MrWardy** [comment]
Nope, thanks
