### ISSUE TITLE
Warning on startup

### ISSUE THREAD

**Issue by Gnat008** [Gnat008/PerWorldInventory#205]
Ref #204 

On startup, users experience `[PerWorldInventory] Could not save default.json to plugins\PerWorldInventory\default.json because default.json already exists.` in the console.

Double check how the default files are saved in `onEnable()`. Unknown if related, but it is also possible that we are moving the defaults file to the right path, but wrong filename (default.json instead of __default.json).

**Comment by gaberilde** [comment]
i get the oppisate error to you...
 im getting default.json dosent exist so renaming it to __default.json works

anyway i have a request feature can  u check it out?

**Comment by Gnat008** [comment]
I'm no longer seeing this behavior with the latest code, so closing this. If it turns out I'm wrong, will re-open.
