### ISSUE TITLE
Inventories not being seperated

### ISSUE THREAD

**Issue by DominusLux** [Gnat008/PerWorldInventory#208]
i have been fighting with this plugin for 4 days now trying to get it to work properly and it just wont. I followed the setup properly yet it still doesnt separate inventories between worlds. I am op on the server and the plugin seperate my inventory, but any of the other regular player ranks just doesnt, theyre able to take stuff into creative world and out of creative world. Its frustrating, because MV-I is outdated and we're recommended to use this instead but it just wont work no matter what i do. while this gets sorted out we're forced to run MV-i which even though it works like it always has, does have some issues.

We're running spigot 1.11.2, config is posted below.
![capture1](https://cloud.githubusercontent.com/assets/27710303/25108692/c409702e-23a5-11e7-8e92-3284b18b025e.JPG)
![capture2](https://cloud.githubusercontent.com/assets/27710303/25108691/c408d47a-23a5-11e7-87ad-638350cdafe8.JPG)

**Comment by Gnat008** [comment]
Well, I don't see any obvious errors. Could you turn on debugging in the config, reproduce the issue with a user, and send me the logs?

**Comment by DominusLux** [comment]
Ok, the issue is that normal players are carrying inventory over to every world as if they have the bypass perm, but they dont, i havent assigned any permissions and it seems to only be seperate OP inventories both between gamemodes and worlds. Ive done what you asked and used a regular player (HarbingerOfDeath) and the results are as shown:
![screen 1](https://cloud.githubusercontent.com/assets/27710303/25113192/f4a9db92-23c3-11e7-8a0f-b131d1e21c8e.png)
this is the output when he went between creative world and survival
![screen 2](https://cloud.githubusercontent.com/assets/27710303/25113203/0959c19c-23c4-11e7-86c1-05f68813136a.png)
this was an output of him just standing still, not sure if itll help

**Comment by Gnat008** [comment]
Now that's interesting... What seems to be happening is that when teleporting, his GameMode changed FIRST, and then the player is teleported. That is the opposite of what happens on my server.... This shouldn't in itself be a problem, except for the fact that the loading of the new GameMode's inventory is happening AFTER he is in the other world and that world's inventory has been loaded.

You used MV-I, so I assume you're still using MultiVerse for multiple worlds?

**Comment by DominusLux** [comment]
Yes we use multiverse for managing multiple worlds, as well as its portal counterpart.

**Comment by Gnat008** [comment]
As do we... hm. Maybe give all players the permission `mv.bypass.gamemode.*` to disable MV managing GameModes, and enable `manage-gamemode` in the PWI config?

**Comment by DominusLux** [comment]
ok, well try that and report back later.

**Comment by DominusLux** [comment]
So, we did what you said and according to PWI debug its apparently still  changing gamemode before teleporting and inventory still carried over. 

![img_18042017_212910_0](https://cloud.githubusercontent.com/assets/27710303/25162556/be4080be-2491-11e7-8b6a-2e506496cf1e.png)
![img_18042017_212944_0](https://cloud.githubusercontent.com/assets/27710303/25162557/be411588-2491-11e7-9970-b506b99265a5.png)
![img_18042017_213120_0](https://cloud.githubusercontent.com/assets/27710303/25162559/be426852-2491-11e7-9900-86e0f7aa0e78.png)
![img_18042017_213156_0](https://cloud.githubusercontent.com/assets/27710303/25162558/be4182de-2491-11e7-8e3b-e1158b7ee977.png)

**Comment by im4g1n4t1onsX** [comment]
You have to convert it. to multiverse with per world inventory

**Comment by DominusLux** [comment]
> You have to convert it. to multiverse with per world inventory

converting didnt change anything, still the same issue
