### ISSUE TITLE
Add config checks for loading player data 

### ISSUE THREAD

**Issue by Gnat008** [Gnat008/PerWorldInventory#21]
Add config checks when loading data so that any data that may be present that is configured to not be saved wont be loaded. Currently, it just assumes that if it is there, it should be used.

**Comment by ExileDev** [comment]
This is something i've been looking into. Do you accept pull request?

**Comment by Gnat008** [comment]
https://github.com/Gnat008/PerWorldInventory/commit/45e871132a8fae3bb07c6ffe9ac8ea826a365329
