### ISSUE TITLE
Will Not Create Config Folder

### ISSUE THREAD

**Issue by NevitOfficial** [Gnat008/PerWorldInventory#211]
My server is running "CraftBukkit version git-Spigot-6016ac7-10c10b3 (MC: 1.10)". And I placed the .jar file in my plugins folder restarted it multiple times and the plugin folder will not create. Is there any other plugin required with this like ProtocolLib? Just let me know.

**Comment by Gnat008** [comment]
Nope. Most likely there is an error on startup. Could you please check your logs/console and paste it here for me?

**Comment by NevitOfficial** [comment]
What is the plugin titled when you do /plugin? Is it titled PerWorldInventory or InventoryPerWorld?

**Comment by Gnat008** [comment]
PerWorldInventory.

**Comment by NevitOfficial** [comment]
Alright, I have a plugin called InventoryPerWorld in there. Ill send you the console in a bit.

**Comment by NevitOfficial** [comment]
[latest-log.txt](https://github.com/Gnat008/PerWorldInventory/files/949389/latest-log.txt)

**Comment by Gnat008** [comment]
Ah. PWI requires Java 8, you have Java 7. You'll have to update Java.

**Comment by NevitOfficial** [comment]
Oh okay! Thank you for the help.

**Comment by Gnat008** [comment]
Not a problem! That's why I'm here.
