### ISSUE TITLE
Player Death Duplicate bug - bed diffrent world

### ISSUE THREAD

**Issue by Pigna** [Gnat008/PerWorldInventory#213]
When a player dies in survival when having his bed set in a diffrent world with not shared inventory his on death inventory will be loaded back in to the player when he returns to the survival world. Making him have double the items becouse of the loaded items and the on death dropped items.

Example:
Player 'nick' has a bed in creative (to make it day).
He goes to survival has 1 diamond sword in his inventory.
He dies in survival and gets returned to his bed in creative.
When he returns to surival he has his sword again.
When he returns to his death location he can pick-up the sword he lost on death.
Conclusion: he has the same sword twice.

Config:
manage-gamemodes: true
separate-gamemode-inventories: true
share-if-unconfigured: false
metrics:
    enable: true
    send-number-of-groups: true
    send-number-of-worlds: true
player:
    economy: false
    ender-chest: true
    inventory: true
    stats:
        can-fly: false
        display-name: false
        exhaustion: true
        exp: true
        food: true
        flying: false
        gamemode: false
        max-health: true
        health: true
        level: true
        potion-effects: true
        saturation: true
        fall-distance: true
        fire-ticks: true
        max-air: true
        remaining-air: true
save-interval: 300t.
load-data-on-join: true
debug-mode: false
disable-bypass: false

Worlds:
groups:
  default:
    worlds:
    - world
    - world_nether
    - world_the_end
    - world_farm
    default-gamemode: SURVIVAL
  creative:
    worlds:
    - world_creative
    - world_freebuild
    default-gamemode: CREATIVE
  kitpvp:
    worlds:
    - world_kitpvp
    default-gamemode: SURVIVAL
  games:
    worlds:
    - world_games
    default-gamemode: SURVIVAL

**Comment by Pigna** [comment]
Made multiverse set all bedspawns off to prevent misuse of this bug. but world love to see it fixed since players can not use beds atm.

**Comment by ScuroK** [comment]
I have same problem on fall damage. They respawn in another world and then go back.
This is a major dupe bug!!

**Comment by BBoyJD10** [comment]
Please fix... i have same issue with fall damage

**Comment by Gnat008** [comment]
Oops, missed this duplicate report. Please see #200 for discussion and updates. :)
