### ISSUE TITLE
Skulls Disappearing from Inventory on Gamemode Change

### ISSUE THREAD

**Issue by CultivateMC** [Gnat008/PerWorldInventory#214]
How to Reproduce: Place skulls in your inventory in creative. Change to survival mode. Skulls will disappears. Affects all types of Skulls except Essentials-created Player skulls (using /skull ign). 

What should happen: Skulls should not be lost on gamemode switch. 

Config: 
manage-gamemodes: true
separate-gamemode-inventories: true
share-if-unconfigured: false
metrics:
    enable: true
    send-number-of-groups: true
    send-number-of-worlds: true
player:
    economy: false
    ender-chest: true
    inventory: true
    stats:
        can-fly: true
        display-name: false
        exhaustion: true
        exp: true
        food: true
        flying: true
        gamemode: false
        max-health: true
        health: true
        level: true
        potion-effects: true
        saturation: true
        fall-distance: true
        fire-ticks: true
        max-air: true
        remaining-air: true
save-interval: 300
load-data-on-join: false
debug-mode: false
disable-bypass: false

**Comment by Gnat008** [comment]
This is intended due to an issue with Spigot throwing errors when a skull does not have valid or complete information.

**Comment by CultivateMC** [comment]
@Gnat008 gone from the inventory entirely.

**Comment by Gnat008** [comment]
Okay, that's odd. Are there any errors in the server console or logs?

**Comment by CultivateMC** [comment]
@Gnat008 nope.

**Comment by CultivateMC** [comment]
@Gnat008 seems to be fixed in 1.11.1. Not sure if anything changed for this but the issue can be closed.
