### ISSUE TITLE
How do I only share exp and money between two worlds.....

### ISSUE THREAD

**Issue by trexguo** [Gnat008/PerWorldInventory#22]
Here is my worlds.yml:

groups:
  default:     # share everything
    worlds:
    - world
    - world_nether
    - world_the_end
    - mine2
    default-gamemode: SURVIVAL
  mini:        # only share exp and money with the default group
    worlds:
    - mini
    # "-world"?
    default-gamemode: ADVENTURE

Is it supported by the plugin? 
I think perhaps we need separate configs for each groups?

**Comment by Gnat008** [comment]
I think to do what you want you would put all worlds that share everything in the same group, like you have now. To have data (in this case, exp and money) shared across groups, set them to false in 'config.yml' so that they won't be saved (and thus, they will be shared).

**Comment by trexguo** [comment]
Thank you for reply but I am still a little bit confused. So are you saying the worlds in the same group will share everything by default and the config.yml is used to determine what to share between different groups?
And for "set the group defaults be using the command, or manually editing the files", what does it mean?

**Comment by Gnat008** [comment]
Your first paragraph is exactly correct.

As for the second, each group has a default loadout for when a player first enters a world. Please see the project description/readme here, or the plugin description on Spigot/DevBukkit for more details.

**Comment by Gnat008** [comment]
Gonna close this one. If you have anything else related to this issue, you should be able to reopen it here.
