### ISSUE TITLE
duplacate bug

### ISSUE THREAD

**Issue by dwa1275** [Gnat008/PerWorldInventory#228]
when players dine in a world, spawn in the main world, then go back, player get double the items, this is a bug that multiverse inventories was able to fix, shouldn't be that hard to fix

**Comment by ScuroK** [comment]
i have the same issue.

**Comment by Gnat008** [comment]
Duplicate of #200. Closing duplicates to clean things up a bit; see that issue for further comments/discussion. Thanks!
