### ISSUE TITLE
Multiple Bugs

### ISSUE THREAD

**Issue by VolcanoMan3705** [Gnat008/PerWorldInventory#229]
Okay. I'm on version Spigot 1.10.2.  I downloaded this plugin to split world's inventories. I started out with 1.10.0, which seemed to work fine. Except for the fact that every time someone died their items would duplicate when they returned to the world, although it uploaded some information cache at a different date. So, I switched to 1.9.0. That fixed it, but now, I have to deal with players losing their EXP on death, when I have it set to not be lost on death. This is seriously a big problem, given that everything on my server scales off of EXP.

https://pastebin.com/SqHPHtK8

**Comment by Gnat008** [comment]
Fixed in v1.11.
