### ISSUE TITLE
Error while parsing config

### ISSUE THREAD

**Issue by MerakiMc** [Gnat008/PerWorldInventory#230]
http://paste.thezomg.com/22462/14982214/ <-- Console log of my error.

http://paste.thezomg.com/22463/49822152/ <--- My config file.

Not entirely sure what I did wrong?

**Comment by ljacqu** [comment]
Bad intentation, your lists aren't indented like in the example given in the comment

**Comment by Gnat008** [comment]
No more activity here, closing.
