### ISSUE TITLE
java.io.FileInputStream.open0(Native Method)

### ISSUE THREAD

**Issue by maxlehot1234** [Gnat008/PerWorldInventory#236]
Hi, I have this error in the console.
https://pastebin.com/hr2jBZ3r
Anyway to fix this error?

**Comment by maxlehot1234** [comment]
No news ??? Any update ?? Any answer?? Any support for your plugin??

**Comment by ljacqu** [comment]
Are you still getting it? Would help if you provided some of the text above and below from the log, what actions (if any) cause this and what server software you're running on.
