### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by CMCosMic** [Gnat008/PerWorldInventory#238]
I'm getting the error in the console...
 

`[00:10:45] [Server thread/ERROR]: Error occurred while disabling PerWorldInventory v1.10.0 (Is it up to date?)`

Is this something wrong or is everyone else getting this?

**Comment by ljacqu** [comment]
What's the rest of the log? I expect there were more errors; this literally just says "something went wrong" so there's not much we can do starting from this.
