### ISSUE TITLE
ANY ETA for the next update that will fix all issues we have?

### ISSUE THREAD

**Issue by maxlehot1234** [Gnat008/PerWorldInventory#242]
Hi, I just want to know if you have an ETA for the next update that will fix all issues we have?

**Comment by TheZenKitteh** [comment]
Based on how little communication there is from the devs, I'm thinking this project is dead, sadly.

**Comment by maxlehot1234** [comment]
Agree with you.... They close tickets and no updates.. Everyone have errors and they should fix these things, not add more thing into the plugin...

**Comment by ljacqu** [comment]
> Everyone have errors and they should fix these things, not add more thing into the plugin...

So in your opinion what was added recently that was misdirected?

**Comment by ljacqu** [comment]
Btw your issue #236 doesn't have much info, and you've never answered my question. As a user you also need to do your part by providing enough info and "owning" your tickets.
