### ISSUE TITLE
Request for InventoryPreLoadEvent

### ISSUE THREAD

**Issue by stefvanschie** [Gnat008/PerWorldInventory#255]
If possible I'd like to see an InventoryPreLoadEvent which can be cancelled. I know there's already an InventoryLoadCompleteEvent, but I need to cancel the inventory loading in some situations before stuff has happened. Cancelling the events this plugin listens for isn't an option either, cause the events still need to take place. An event like this would really help fix some compatibility issues between this one and my plugin.

I was thinking about the InventoryPreLoadEvent being fired here: https://github.com/Gnat008/PerWorldInventory/blob/master/src/main/java/me/gnat008/perworldinventory/data/players/PWIPlayerManager.java#L246

If you want I'd also be happy to make a pull request for this, if you prefer that.

**Comment by Gnat008** [comment]
I like this idea, I'll see what I can do. Or if you do something before I do, that can work too. xD
