### ISSUE TITLE
error on changing worlds with different gamemodes

### ISSUE THREAD

**Issue by Paxination** [Gnat008/PerWorldInventory#26]
http://pastebin.com/Xrmu11n4

Getting that error when switching worlds in different groups that my player has a different gamemode.  Switching gamemodes does it too.

Running Spigot 1.8.7

PWI 1.5.4

**Comment by Gnat008** [comment]
Can you post your config please?

**Comment by Paxination** [comment]
first-start: true
manage-gamemodes: false
separate-gamemode-inventories: true
player:
  economy: true
  ender-chest: true
  inventory: true
  stats:
    can-fly: true
    display-name: false
    exhaustion: true
    exp: true
    food: true
    flying: true
    gamemode: true
    health: true
    level: true
    potion-effects: true
    saturation: true

**Comment by Gnat008** [comment]
@Paxination 
For now, set the gamemode saving option to off.

**Comment by Paxination** [comment]
When can we expect a release for this?

**Comment by Paxination** [comment]
@Gnat008 When can we expext a release for this?  Its sorta a game breaker for us.

**Comment by Gnat008** [comment]
@Paxination 
Sorry, was unexpectedly without internet. Expect a plugin update today.
