### ISSUE TITLE
Error on InventoryLoadEvent

### ISSUE THREAD

**Issue by Tiippex** [Gnat008/PerWorldInventory#263]
![ErrorPanel](http://tiippex.de/pics/i//q2jdd.png)

**Comment by Gnat008** [comment]
@Tiippex Does this version fix it? https://drive.google.com/open?id=0B7hS84xeTkpsU0pVbjVjS3VySTA

**Comment by Tiippex** [comment]
Looks good at the moment. I can give a correct answer in a few days.

**Comment by Gnat008** [comment]
I can confirm that there are no errors and everything works as expected again on my server.
