### ISSUE TITLE
Problem with DynamicStands - Caused by PWI?

### ISSUE THREAD

**Issue by ScuroK** [Gnat008/PerWorldInventory#265]
Hi im using Vehicles from the DynamicStands - Plugin.
Im having problems with the vehicles and the dev is asking me if i have any plugins which opens an inventory on teleport. since i dont have any plugins doing this im wondering if PWI does anything like that.

Here is an error log:
https://pastebin.com/bWS0u89k

**Comment by Gnat008** [comment]
Assuming that by "opens an inventory" he means opens like an inventory GUI (where the displayed items act as buttons), then no, PWI doesn't do anything like that.

**Comment by ScuroK** [comment]
The issue is not related to pwi but to protocollib. Close
