### ISSUE TITLE
Bypass gamemode

### ISSUE THREAD

**Issue by KillerOfPie** [Gnat008/PerWorldInventory#266]
https://github.com/Gnat008/PerWorldInventory/blob/c7fe80f2f5f05c8dd543680380b69a0cfb745ca9/src/main/java/me/gnat008/perworldinventory/process/GameModeChangeProcess.java#L49

Pretty sure that you used the wrong permission here. Should be BYPASS_ENFORCEGAMEMODE
This creates a decent problem for my staff as we use spectator mode to watch players and changing worlds would pull them out of it.

**Comment by Gnat008** [comment]
Mm nope, that permission is correct there. If a player has that permission, their inventory will not change when switching gamemodes. `BYPASS_ENFORCEGAMEMODE` makes it so that a player with that permission will not have their gamemode changed when switching worlds. So if your staff has `BYPASS_ENFORCEGAMEMODE` and their gamemode is changing, it's likely another plugin. Depending on certain settings, MultiVerse likes to do that.

**Comment by KillerOfPie** [comment]
@Gnat008 do you know what in multiverse would do it?

**Comment by Gnat008** [comment]
Mm I'd have to play around with it; I forget what does it every time. I know it's something stupid. Lemme see if I can find it.

**Comment by KillerOfPie** [comment]
@Gnat008 Thanks, I'll dig around and see if i can find something

**Comment by Gnat008** [comment]
Ah, I might have found it. Try giving them the permission `mv.bypass.gamemode.*`

**Comment by KillerOfPie** [comment]
@Gnat008 Works, thanks. Hadn't looked through all of mv's perms yet. And sorry for misreading code :p

**Comment by Gnat008** [comment]
Not a problem! And I'm not even sure if that perm is listed; I stumbled across it one day trying to figure out a similar issue on the Spigot forums.

**Comment by KillerOfPie** [comment]
@Gnat008 its at the bottom of access permissions. Another question though, do you know of any way to be more specific about gm changes, like if i don't want it to change staff out of spectator mode but i do want it to change them out between creative and survival?

**Comment by Gnat008** [comment]
I would think just giving them the perm `mv.bypass.gamemode.spectator` would do what you want, instead of `.*`. Assuming it does what I think it does, anyway.

**Comment by KillerOfPie** [comment]
@Gnat008 tried and no it uses world so it wont change their gamemode when entering a certain world

**Comment by Gnat008** [comment]
Oh. Well, in that case... I think that might be the best you can do, unless there's something I don't know about.

**Comment by KillerOfPie** [comment]
@Gnat008 alright, thanks. Guess ill have to figure something out
