### ISSUE TITLE
[Suggestion/Question] Blacklist items to be transfered between world

### ISSUE THREAD

**Issue by maxlehot1234** [Gnat008/PerWorldInventory#293]
Hi, I just want to know if you can add something that will prevent players to bring OP pickaxe from default world to the free world for example, but share EVERYTHING else.

It could be really nice to be able to blacklist few items

**Comment by BeatlesDev** [comment]
I'm sorry, but this wouldn't work. If you were to go to the "free world" and fill up you inventory but then went back to the "default world" where your pickaxe is, then where would the pickaxe go? I suggest just separating the inventory or finding some other easy fix for your issue.

Thanks anyways!
