### ISSUE TITLE
PWI compatibility with RestrictedCreative

### ISSUE THREAD

**Issue by Prunt** [Gnat008/PerWorldInventory#312]
I tried to contact the PWI author via PM, but got no response, so I decided to post it here as well in the hopes that it will get noticed:

> I'm the author of RestrictedCreative plugin and I want to make your plugin compatible with mine. The problem, currently, is that my plugin has different inventories for survival and creative mode, but when your plugin is installed, it gets messy (like described here: https://github.com/Prunt/RestrictedCreative/issues/18).
> 
> Do you have any suggestions on how to fix this? I tried listening to your plugin's events, but they're not fired when player is just switching gamemodes.

**Comment by Gnat008** [comment]
Your users might try disabling the 'separate-gamemode-inventories' option in their PWI configs; that way, PWI won't do anything on GameMode changes. Worth a shot to see if that helps, anyway.

**Comment by Prunt** [comment]
Thank you, it worked! I don't know why didn't I think of looking in the config before.
