### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by laurensvdt** [Gnat008/PerWorldInventory#39]
if someone left the server the inventory is cleared ???

why?

**Comment by Gnat008** [comment]
What other plugins do you have? This is not something PWI does.

**Comment by ianblankg** [comment]
im having random inventory wipes too

**Comment by Gnat008** [comment]
Could you guys enable debugging in the config file, run the server until it happens, then send me the logs?

**Comment by aycgit** [comment]
i would check your diskspace and try to debug as gnat said, and i would change this issue title to "inventory getting cleared after logout"

**Comment by Gnat008** [comment]
Never heard back, going to assume this is resolved. Please reopen if this is in error.
