### ISSUE TITLE
???help

### ISSUE THREAD

**Issue by MissTomiz** [Gnat008/PerWorldInventory#41]
Hi, 
So i downloaded the plugin and when i installed it to my server it just acted like its not even there?? like ill do /pwi help and nothing shows up. there's no error or anything on the console and also everyone has the same inventory for each world. this seems like a really great plugin and im so sad that it doesnt work :( please help!

**Comment by Gnat008** [comment]
Could you show me your full startup log?

**Comment by MissTomiz** [comment]
http://pastebin.com/0cQjY9W1

**Comment by Gnat008** [comment]
Can you show me both your config.yml and worlds.yml file? Your YAML is invalid.

**Comment by MissTomiz** [comment]
http://pastebin.com/Jzsg5Tn1 config.yml
http://pastebin.com/VcLgukL0 world.yml

**Comment by Gnat008** [comment]
A lot of the spacing in your worlds.yml file is off. Make sure all lines are indented by a multiple of 2 (that means 2, 4, 6, etc.). Paste it all into http://www.yamllint.com and it will tell you if it is valid or not.

**Comment by MissTomiz** [comment]
it worked!!! thank you so much!!!
