### ISSUE TITLE
Plugin not working, no errors

### ISSUE THREAD

**Issue by PAINmatrix** [Gnat008/PerWorldInventory#42]
The plugin is simply not working. There are no console errors at all, even in debug mode. I have 3 worlds, test, world, and world_nether. There are a few different things that have happened when I was testing it. After I gave myself items in each world, I noticed that 2 of the worlds were sharing inventories, even though they were not configured to and 'share-if-unconfigured:' was false. After a restart, I joined and all of the items I gave myself were gone. I gave myself the items again, and the worlds seemed to separate as they should, but once I restarted again to make sure they stayed that way, I joined and I only had the items in the world I left in. In the other 2 worlds my inventory was empty. One of the times testing this, I got 1 error, but I haven't received it sense and it is still doing the same thing. Here it is: http://pastebin.com/nUYhMKuy

Version 1.7.5 for PWI
Version 1.10 for MC

Config: http://pastebin.com/Y1LXKZPk
Worlds: http://pastebin.com/P5F9WbWs

**Comment by Gnat008** [comment]
During your tests, were you an Op?

**Comment by PAINmatrix** [comment]
@Gnat008 
No. I made sure I was not before I tested this.

**Comment by Gnat008** [comment]
I don't suppose you could send me your server log after turning on debug mode and switching worlds? Also your worlds.yml would be helpful so I know what I'm looking at.

**Comment by PAINmatrix** [comment]
I edited the post. The worlds.yml is at the bottom. Here is my log: http://pastebin.com/2N4f4qLZ

**Comment by Gnat008** [comment]
Could you tell me what other plugins you currently have installed?

**Comment by PAINmatrix** [comment]
The only other plugin is Multiverse, v2.5.0 snapshot.

**Comment by Gnat008** [comment]
Interesting... This may be the first logged confirmation of the random problem some other people experienced. Would I be able to join the server you're using for testing (or whatever this is) to see for myself?

**Comment by PAINmatrix** [comment]
If that is what you would like to do, yes. Try the IP 24.101.73.19:25543. If that does not work say so and I'll set up a hostname.

**Comment by Gnat008** [comment]
For reference: Issue not present during further testing, likely a corrupted MultiVerse download.
