### ISSUE TITLE
Bug duplicate inventory

### ISSUE THREAD

**Issue by Blamo27** [Gnat008/PerWorldInventory#43]
Sometimes, we don't know why or how, players change world and they keep the inventory they had in the previous world they were in, even though they are not supposed to (because these worlds have separated inventories). As a result, the player duplicates his inventory from the previous world, thus deleting the inventory he was supposed to have in the second world.

Spigot version: 1.8.8
I don't want to try the newest versions like 1.7.5, because of comments about this version.

**Comment by Gnat008** [comment]
What version are you using now?
Could you paste your worlds.yml file to hastebin and link it here?

**Comment by Blamo27** [comment]
Version 1.5.10
Yes I will

**Comment by Blamo27** [comment]
http://pastebin.com/hLb4CsaD

**Comment by Gnat008** [comment]
Are there any errors in the console or logs when this happens?

**Comment by Blamo27** [comment]
No errors :/

**Comment by Gnat008** [comment]
1.5.10 is pretty old by this point. If you have a test server, I highly recommend trying the latest version there to make sure everything is set up properly. It could be extremely difficult to figure out what is going on without the new debug messages. Is this a possibility?

**Comment by Blamo27** [comment]
We are going to put the new version on a test server, but that probably won't help at all because of the difficulty to reproduce the issue. It only happens some times, with certain players. We could switch world a thousand times without any problem, and then suddenly it would happen : we can't know for sure, because we don't know what triggers it.

**Comment by Gnat008** [comment]
Huh. That is really weird.

**Comment by Blamo27** [comment]
So, we tried the new version on the test server, and it seems to work fine but we can't know for sure, of course. We will now try to update on the main server and see if the issue persists. I will update this thread if the bug occurs again despite the update. If the bug appears to be gone, I will notify it in a few days.

**Comment by Gnat008** [comment]
Cool. If it persists, can I ask you to set the debugging to true in the console? Even if it takes more time, it's the best way to know exactly what's going on.

**Comment by Blamo27** [comment]
Yes okey :)

**Comment by Blamo27** [comment]
@Gnat008  I will do that, thank you for your time.

**Comment by Blamo27** [comment]
We had a new issue today : a player disconnected in world A, reconnected (still in world A) but had his inventory from world B (he shouldn't). However the issue we talked about previously did not occur... Yet.

I'm going to wait one of this issue pops again to put the debugging to true, just to be sure.

**Comment by Gnat008** [comment]
Is the config option 'load-data-on-join' set to true or false?

**Comment by Blamo27** [comment]
It's on false, but isn't it an 1.9 option ? Our server is on 1.8. Just so you know, however, we installed something to allow people on 1.9 to join our 1.8 server, and the player who had the issue I mentioned (disconnecting-reconnecting) was on 1.9. Don't know if it can affect anything.

**Comment by Gnat008** [comment]
Oh right. Forgot that detail.

**Comment by Gnat008** [comment]
Is this still an issue on the latest version?

**Comment by geb00** [comment]
I'm having this issue and I have the latest version... i think it's also the same issue as [https://github.com/Gnat008/PerWorldInventory/issues/138](url)

**Comment by geb00** [comment]
also i set load data on join to true so......

**Comment by Gnat008** [comment]
Update has been released on Spigot.
