### ISSUE TITLE
Manage-gamemodes does nothing when turned on

### ISSUE THREAD

**Issue by TehProgrammer** [Gnat008/PerWorldInventory#44]
I have checked and double checked the proper way to make it work, and I will not change my gamemode moving from world to world.  I use bukkit with minecraft 1.10.

Also, there should be an in game command to add worlds to the worlds.yml file for you.

**Comment by seema84** [comment]
i can confirm ... this broke this plugin totally

**Comment by seema84** [comment]
no fix gnat?

**Comment by Gnat008** [comment]
Currently the option only works if 'separate-gamemode-inventories' is also turned on. This does not make sense, but also seems to break things if changed.
