### ISSUE TITLE
Economy Help

### ISSUE THREAD

**Issue by heckabecca** [Gnat008/PerWorldInventory#45]
Is it possible to set it so players have separate inventories per gamemode, but the same balance across the board?

**Comment by Gnat008** [comment]
Do you mean all worlds should have the same balance?

**Comment by heckabecca** [comment]
Yea, same balance in each world in any gamemode the player may be in...

**Comment by heckabecca** [comment]
Here is my config and my world files.
[config.txt](https://github.com/Gnat008/PerWorldInventory/files/322412/config.txt)
[worlds.txt](https://github.com/Gnat008/PerWorldInventory/files/322413/worlds.txt)

**Comment by heckabecca** [comment]
I figured it out, had to delete my data folder then reinstall the plugin, copied over the config files (changed the economy to false under player in the config) and now its keeping the same balance. :)
