### ISSUE TITLE
Warn to console

### ISSUE THREAD

**Issue by x0Z3ro0x** [Gnat008/PerWorldInventory#47]
Here is a paste bin on the issue. It wouldn't be much of a problem if it didn't spam the console over and over. I restart my server to get rid of it, but then randomly bam, it happens again. Please take a look and fix if possible.

http://pastebin.com/QwdgeRqi

**Comment by Gnat008** [comment]
When does this happen exactly? From players normally changing worlds?

**Comment by Gnat008** [comment]
Never heard back, going to assume this is resolved. Please reopen if this is in error.
