### ISSUE TITLE
plugin not working correctly

### ISSUE THREAD

**Issue by tricx01** [Gnat008/PerWorldInventory#49]
the plugin kinda works but is also sorta broken i have a creative,survival/factions,skyblock and spawn world the spawn world and the survival world are connected, it sometimes loads the items when changing between worlds that are in the same group but if i go to another and then spawn or another world thats not in the same group
it deletes all items

**Comment by Gnat008** [comment]
Could you show me your worlds.yml?
Also please turn the debugging option in the config on, reproduce the issue, and send me your server log.

**Comment by tricx01** [comment]
http://pastebin.com/1jj7NF40
![udklip](https://cloud.githubusercontent.com/assets/20049016/16203264/b7f70bd0-3719-11e6-9880-954889dfbc3b.PNG)
![udklip2](https://cloud.githubusercontent.com/assets/20049016/16203266/b90b4540-3719-11e6-8571-11f85772c58d.PNG)

**Comment by Gnat008** [comment]
Are you sure that your items aren't in a different gamemode inventory? Currently you have them separated.

**Comment by tricx01** [comment]
yep

**Comment by benjozork** [comment]
I think I am having the same issue. It looks like it happens when new players come to a world for the first time. On my creative server players get their creative inv when they enter the survival world for the first time.

**Comment by Clashica** [comment]
agreed with benjozork

**Comment by tricx01** [comment]
well disabling separate-gamemode-inventories works, but it breaks manage-gamemodes

**Comment by tricx01** [comment]
i have found a fix with multiverse though

**Comment by Gnat008** [comment]
So turning off the gamemode separation worked?

**Comment by Clashica** [comment]
doesnt work for me Gnat like right when i turned it to false it made it work for 10 minutes then broke

**Comment by Gnat008** [comment]
Do any of you have a server I could join to see for myself? Sometimes that helps.

**Comment by Clashica** [comment]
167.114.1.89:25663

**Comment by Gnat008** [comment]
These issues I believe are resolved now.

**Comment by benjozork** [comment]
How did you resolve the issues ? You didn't even introduce a fix...
