### ISSUE TITLE
pwi not doing anything

### ISSUE THREAD

**Issue by aycgit** [Gnat008/PerWorldInventory#52]
issue: see title
debug also isnt doing anything 

worlds
[worlds.txt](https://github.com/Gnat008/PerWorldInventory/files/333078/worlds.txt)
no errors to see
spigot 1.8.8
plugin version 1.7.5
if u know what is the problem please tell me
i grabbed the download from the spigot page

**Comment by Gnat008** [comment]
Can you try the latest version and see if the problem still exists? It could be you were getting the bypass permission if you were Op, even if you aren't supposed to.

If the problem still persists, please turn on debugging in the config, restart the server, reproduce the issue, and send me your server log.

**Comment by aycgit** [comment]
debugging is fixed in the new version and i saw this
 [DEBUG] Player 'Wereld2003' has 'perworldinventory.bypass.world' permission! Returning


edit:
i think ive seen the fix, groupmanager automaticly gave me the * permission and i guess thats why it failed
thanks for the help tho
