### ISSUE TITLE
Player getting killed when died once, infinitely.

### ISSUE THREAD

**Issue by Guuss** [Gnat008/PerWorldInventory#53]
##Hey there.
I have got an issue, where when a player dies in a world when the inventory is managed by PWI, and the player tries to respawn, he keeps getting killed infinitely, no matter what world they are in. I can't show any logs because there is literally nothing to show, it just keeps killing the player.
As soon as you give the player a starnode for PWI, he does not get killed though.

If you want further information, add me on Skype: live:nervednetwork_1

Kind regards,
Guus

**Comment by aycgit** [comment]
this issue should be fixed with that commit? is it fixed guuss?

**Comment by Gnat008** [comment]
The fix will be released on Spigot in the near future. At that point I'll ask you to verify that the issue is fixed on your end.

**Comment by Guuss** [comment]
A possible fix is to simply delete the player data file of the player whom it concerns. That fixed it.

**Comment by Gnat008** [comment]
That's a workaround. The fix is setting their health to max since they died and respawned.

**Comment by Guuss** [comment]
I'll give it a go, cheers.

**Comment by Gnat008** [comment]
Wait a minute, that will wipe their inventory. Duh

**Comment by Guuss** [comment]
Deleting the file?

**Comment by Gnat008** [comment]
Yes. Since that is where their inventory and all other data is stored.

**Comment by Guuss** [comment]
I know yes, but I simply had them hand over the items for a second, delete the file and then give it back. It was only two players who had this problem.

**Comment by Gnat008** [comment]
Fix released on Spigot. Could you please confirm this is fixed on your end?

**Comment by Gnat008** [comment]
@Guuss ?

**Comment by Guuss** [comment]
@Gnat008 Heyo, sorry. I was on holiday in Greece, back now though. I will be testing it soon, migrating the server to a diffrent provider at the moment. I'll let you know!

**Comment by Gnat008** [comment]
Never heard back, going to assume this is resolved. Please reopen if this is in error.

**Comment by Guuss** [comment]
This particular issue is resolved. My lead developer ran into more issues with PWI though regarding Multiverse and nether worlds. I can't exactly tell you what the issue is, something with the inventory not carrying over properly. I can get you in contact with him if you'd like, he will be able to point it out much better than me.

But yes, issue resolved. Requesting lock-down of this thread now.
