### ISSUE TITLE
Big Error on connect

### ISSUE THREAD

**Issue by Wasabules** [Gnat008/PerWorldInventory#54]
28.06 03:36:58 [Server] ERROR Could not pass event PlayerSpawnLocationEvent to PerWorldInventory v1.7.6
28.06 03:36:58 [Server] INFO org.bukkit.event.EventException
28.06 03:36:58 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-c3e4052-1953f52]
28.06 03:36:58 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-c3e4052-1953f52]
28.06 03:36:58 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-c3e4052-1953f52]
28.06 03:36:58 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-c3e4052-1953f52]
28.06 03:36:58 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerList.a(PlayerList.java:114) [spigot.jar:git-Spigot-c3e4052-1953f52]
28.06 03:36:58 [Server] INFO at net.minecraft.server.v1_10_R1.LoginListener.b(LoginListener.java:144) [spigot.jar:git-Spigot-c3e4052-1953f52]
28.06 03:36:58 [Server] INFO at net.minecraft.server.v1_10_R1.LoginListener.E_(LoginListener.java:54) [spigot.jar:git-Spigot-c3e4052-1953f52]
28.06 03:36:58 [Server] INFO at net.minecraft.server.v1_10_R1.NetworkManager.a(NetworkManager.java:233) [spigot.jar:git-Spigot-c3e4052-1953f52]
28.06 03:36:58 [Server] INFO at net.minecraft.server.v1_10_R1.ServerConnection.c(ServerConnection.java:140) [spigot.jar:git-Spigot-c3e4052-1953f52]
28.06 03:36:58 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:832) [spigot.jar:git-Spigot-c3e4052-1953f52]
28.06 03:36:58 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-c3e4052-1953f52]
28.06 03:36:58 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot.jar:git-Spigot-c3e4052-1953f52]
28.06 03:36:58 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot.jar:git-Spigot-c3e4052-1953f52]
28.06 03:36:58 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
28.06 03:36:58 [Server] INFO Caused by: java.lang.NullPointerException
28.06 03:36:58 [Server] INFO at me.gnat008.perworldinventory.listeners.player.PlayerSpawnLocationListener.onPlayerSpawn(PlayerSpawnLocationListener.java:65) ~[?:?]
28.06 03:36:58 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
28.06 03:36:58 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
28.06 03:36:58 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
28.06 03:36:58 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
28.06 03:36:58 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-c3e4052-1953f52]

**Comment by Gnat008** [comment]
Could you please send me the "last-location.json" file for someone causing the error?

**Comment by Gnat008** [comment]
Never heard back, going to assume this is resolved. Please reopen if this is in error.
