### ISSUE TITLE
Plugin Not Working at all.

### ISSUE THREAD

**Issue by blacktsumi** [Gnat008/PerWorldInventory#60]
i just cannot get this plugin too work, i do not want the default worlds (World, Nether & the end)  too share anything with the minigame world at all, i just dont get it why it's not working?

PasteBin's:
- http://pastebin.com/9SnmdWNL <- World
- http://pastebin.com/GjLFhNtK <- Config
- http://pastebin.com/YEnnDPxS <- Error

**Comment by Gnat008** [comment]
I think your links are broken, could you try again?

**Comment by blacktsumi** [comment]
It's one of the most perfect plugins ive seen yet soo it feels very bad for it too not work because i did something wrong.

There is no permissions that is needed too be given too make it work for basic players rite?
the only permissions i saw was if you wanted too give an group bypass permissions.

**Comment by Gnat008** [comment]
Correct. But your links above don't work. Could you fix those of paste new ones for me please?

**Comment by blacktsumi** [comment]
They should be alright now.

**Comment by Gnat008** [comment]
Ah, I had to refresh. Will soon push a change that should fix this and #59

**Comment by Gnat008** [comment]
Also, what server version are you running?

**Comment by blacktsumi** [comment]
Good too hear :) i think there is alot of people that might have the same problem.
Version: Craftbukkit 1.10.(0-2)

**Comment by Gnat008** [comment]
Fix released on Spigot. Could you please confirm this is fixed on your end?

**Comment by blacktsumi** [comment]
will do right away

**Comment by blacktsumi** [comment]
"errors" - http://pastebin.com/SVt76h1Z

i want the 3 basic worlds too share (survival) but not with the minigame one. is this config correct?

Worlds - http://pastebin.com/DetAr1hH
Config - http://pastebin.com/jquDXjCA

it might just be me :P

**Comment by Gnat008** [comment]
Your worlds.yml should be:
`groups:
  default:
    worlds:
    - world
    - world_nether
    - world_the_end
    default-gamemode: SURVIVAL
  minigames:
    worlds:
    - minigame
    default-gamemode: SURVIVAL`

This is unrelated to this issue, so if you have further issues, please open a new one.

**Comment by blacktsumi** [comment]
other than that the plugin does not give the first error. 

VERIFIED

**Comment by Gnat008** [comment]
Thanks!
