### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Rodrogamby** [Gnat008/PerWorldInventory#69]
Not matter what I do, I'm using spigot 1.10, the worlds have the same inventory, I've already world groups, but nothing happens.

**Comment by Gnat008** [comment]
Could you please attach your worlds.yml file?

Additionally could you enable debugging in the plugin config, reproduce the issue, and attach your server log file here?

**Comment by Gnat008** [comment]
Never heard back, going to assume this is resolved. Please reopen if this is in error.
