### ISSUE TITLE
Exception PlayerSpawnLocationEvent

### ISSUE THREAD

**Issue by sigmaroot** [Gnat008/PerWorldInventory#70]
Please take a look at this:

http://pastebin.com/e8eNeKgc

Updating from 1.5.10 to 1.7.8 @ testing server

**Comment by sigmaroot** [comment]
After this error, inventory is not saved correctly:

http://pastebin.com/1JNTmb02

Look @ lines 13 and 38/39. PWI is allegedly adding ...builder.survival to cache @ line 13 but cannot find any data @ line 38 / 39 and is reloading it from the file, again. This causes loss of all changes made between this two timestamps.

**Comment by Gnat008** [comment]
Could you give me a copy of the data file that causes the error in the first post?

**Comment by sigmaroot** [comment]
[builder.json](http://pastebin.com/LHsvdei9)

**Comment by sigmaroot** [comment]
Nobody is answering, I'm giving up. Guess I'm going to switch to another plugin.

**Comment by sigmaroot** [comment]
Reopen for further fixes.

**Comment by sigmaroot** [comment]
Reopen for futher fixes.

**Comment by Gnat008** [comment]
Is this still a problem on the latest version?

**Comment by sigmaroot** [comment]
I'm going to verify this as soon as possible but this may take some time due to 1.11 updating tasks.

**Comment by sigmaroot** [comment]
Seems to be fixed.
