### ISSUE TITLE
World Inventory Sharing

### ISSUE THREAD

**Issue by N1CK1238** [Gnat008/PerWorldInventory#76]
Hey,

I don't know if this feature is available, but if it is not, then please consider this as a feature request.
I would like a feature where we can share the same inventory within select worlds (i.e. we keep the same inventory for Factions and KitPvP but get a different inventory for a mini games world).

Thank you!

**Comment by Gnat008** [comment]
No idea why this is still open with no replies, but this is a core feature of the plugin. :)
