### ISSUE TITLE
Fatal Error causing plugin not to work.

### ISSUE THREAD

**Issue by alexp9982** [Gnat008/PerWorldInventory#77]
Whenever I start up the server, I receive the following errors:

03.08 17:16:56 [Server] INFO Enabling PerWorldInventory v1.7.8
03.08 17:16:56 [Server] INFO Registering commands...
03.08 17:16:56 [Server] INFO Commands registered! Registering listeners...
org/spigotmc/event/player/PlayerSpawnLocationEvent does not exist.
03.08 17:16:56 [Server] ERROR Plugin PerWorldInventory v1.7.8 has failed to register events for class me.gnat008.perworldinventory.listeners.player.PlayerSpawnLocationListener because org/spigotmc/event/player/PlayerSpawnLocationEvent does not exist.
Registered PlayerGameModeChangeListener.

Others then that there is nothing that has to do with the plugin in the console, but the plugin itself does not work.

**Comment by Gnat008** [comment]
Can you give me the output of /version?

**Comment by alexp9982** [comment]
Certainly

**Comment by alexp9982** [comment]
This server is running CraftBukkit version git-Bukkit-0cd0397 (MC: 1.9.4)
(Implementing API version 1.9.4-R0.1-SNAPSHOT)

**Comment by Gnat008** [comment]
Well, I'd guess that event doesn't exist in CraftBukkit, only Spigot. Thaaaanks Spigot....
Okay, as a workaround, you could switch to Spigot, there really is no reason not to anyway. I'll mark this as a bug as well, but I can't guarantee that the fix will be released soon.

**Comment by Gnat008** [comment]
Fixed by 55cfa8aca9430175566622be4c644a2c58dee002
