### ISSUE TITLE
Not saving to file after rejoin + quit

### ISSUE THREAD

**Issue by sigmaroot** [Gnat008/PerWorldInventory#78]
When a player joins, quits, re-joins and quits, the second quit is not saved to file immediatly (except the world the player logs out). It is possible to double the inventory.

Steps:

Login World A
Logout World A

Login World A
Teleport World B
Drop Item To Ground
Teleport World A
Logout World A

Login World A
Teleport World B
INVENTORY IS NOT CHANGED! Pick up dropped item to double it!

**Comment by sigmaroot** [comment]
Similar to #70, I'm not using this plugin anymore, due to too many major bugs.

**Comment by sigmaroot** [comment]
Reopen for further fixes.

**Comment by Gnat008** [comment]
Er was this meant to be closed?

**Comment by sigmaroot** [comment]
Yes, I'm giving up... I can't trust that plugin anymore and I'm suspending tests and bug-reports.

**Comment by sigmaroot** [comment]
Reopen for futher fixes.

**Comment by Gnat008** [comment]
The commit to fix this is already done, actually. Just doing a few more things for a major release.

**Comment by sigmaroot** [comment]
Yes, I've read something similar on spigot. Thanks.

**Comment by Gnat008** [comment]
This was fixed by d8ada419ffc74240c0f15ae6423bcf8a26a96bda
Not sure why I left this open.
