### ISSUE TITLE
Share Inventories.. (I dont want it)

### ISSUE THREAD

**Issue by GamingFuture** [Gnat008/PerWorldInventory#82]
Hey guys, every Inventory will be shared on my Server, i dont know why.
I need help.. :( 

config.yml:
http://pastebin.com/r92bDhVK

worlds.yml
http://pastebin.com/jVszrb7U

Thank you very much in advance for your answer.

**Comment by aycgit** [comment]
u messed up your yml

**Comment by Gnat008** [comment]
The spacing and naming in your worlds.yml is all messed up. Try looking over it carefully, and note the example at the top.

**Comment by Gnat008** [comment]
Never heard back, going to assume this is resolved. Please reopen if this is in error.
