### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by XenonsMC** [Gnat008/PerWorldInventory#84]
For some reason randomly the plugin stopped working and all inventories are carried around, i tried re installing plugin, nothing helped, reset config, nothing again

**Comment by aycgit** [comment]
errors? logs? have u tried to reset the config? config? have u made sure that u didnt accidently disabled it? we really need more information to know what is wrong

**Comment by Gnat008** [comment]
No details or info after so long, going to close. Any further issues, please open a new one with details.
