### ISSUE TITLE
StartUp Bug

### ISSUE THREAD

**Issue by DutchUser** [Gnat008/PerWorldInventory#85]
Server: git-Spigot-6016ac7-10c10b3 (MC: 1.10) (Implementing API version 1.10-R0.1-SNAPSHOT)

http://pastebin.com/icAgpdGS

Our server crashed and after that he give this error everytime. Can this fix whitout players lose ther items?

**Comment by Gnat008** [comment]
Pretty sure this is fixed in one of the versions between your current version and the latest PWI version. Try updating the plugin.

**Comment by Gnat008** [comment]
Haven't heard back, going to assume fixed by now.
