### ISSUE TITLE
Swap Inventory to World

### ISSUE THREAD

**Issue by AndrewMast** [Gnat008/PerWorldInventory#87]
Is it possible to swap an inventory from one world with another?

**Comment by Gnat008** [comment]
Mm You could swap the names of the data files. Keep in mind though that the players will still log in with whatever items they logged out with, regardless of the files.

**Comment by AndrewMast** [comment]
Is there a command to move a player's inventory from one world to another?

**Comment by Gnat008** [comment]
Not currently. I suppose one could be added... Assuming you mean the saved inventories. I don't believe there is any easy way to change what they logged out with.

**Comment by AndrewMast** [comment]
So there is no possible way to transfer a player's current inventory from one world to another? I don't get it 'what they logged out with.'

**Comment by Gnat008** [comment]
Okay, let me try explaining it more verbosely.

The items you are carrying (your inventory) at any given time are tracked and handled by Minecraft itself. When you log out, this gets saved to your .dat file. When you log back in, the server looks in that .dat file, and gives you those items. This file is not touched at all by PWI.

PWI saves data in its own plugin folder. These are only looked at when a player changes their gamemode, or they change worlds.

Therefore, when a player logs out from the server, they will still get the items they had when they last logged out, regardless of what is saved by PWI. I suppose I could force the loading of player inventories when they join the server, but I don't know if that would cause issues with anything like other plugins.

**Comment by AndrewMast** [comment]
Okay. Imagine a server with a hub/lobby. Whenever you join the server, you are in the lobby. You select a sub-server to join and then your inventory is restored to what it was when you logged off or went to the lobby.

Technically, since you logged off and it already set your inventory to something else (in the lobby), PWI should be storing my inventory for each sub-server and could be switched, correct?

(P.S: Thanks for the quick replies)

**Comment by Gnat008** [comment]
Err each server would be separate.

**Comment by AndrewMast** [comment]
What do you mean that each server would be separate?
