### ISSUE TITLE
Custom Heads are not properly handled/saved and become steve heads

### ISSUE THREAD

**Issue by Flexo013** [Gnat008/PerWorldInventory#88]
Heads that are generated without a playername are not saved properly. Heads are made using this website: http://heads.freshcoal.com/maincollection.php

The heads do not have an associated playername. They have a UUID, which is a random UUID placeholder, so this can't be used to store the head. You need to store the NBT data on the head that provides the link to the actual skin.

**Comment by Gnat008** [comment]
This is intended as this causes Spigot to throw errors otherwise due to missing data.

**Comment by Flexo013** [comment]
What errors are you talking about? Could you send them to me?

Then I will see if I can get this fixed on Spigot's end first. Since this is a vanilla feature that would be nice to use on Spigot servers.

FYI there are a few plugins out there that utilize these heads in inventories and they are able to store them as well. (And there are no spigot errors on building or executing.) They are not inventory storage plugins like PWI however.
