### ISSUE TITLE
New world and new game

### ISSUE THREAD

**Issue by anemul** [Gnat008/PerWorldInventory#89]
I have added a new world and game , after clicking the join sign I am suppose to get some Lobby Items , but I don't . A little more detail : I have the new world set to Adventure and when I click on the join sign no items , but if I set my gamemode to survival and click the sign the items show up . I have the world set Adventure to prevent people from tearing up the lobby . How do I fix this or is this a bug ?

**Comment by Gnat008** [comment]
Sounds like the items are getting added to the player's inventory while they are still in survival mode. Then, when they get switched to adventure mode, they get their adventure mode inventory.

I suppose there are a couple options here:

1) Is it crucial that your players have a different inventory for each gamemode? If not, you could disable 'separate-gamemode-inventories' in the PWI config.

Or

2) You could not switch their gamemode to adventure mode and instead use a land protection plugin to protect the spawn area.

**Comment by anemul** [comment]
That is what I have done I used WorldGuard to protect the lobby prior to joining the game .
