### ISSUE TITLE
Logout Causing Experience to be Lost

### ISSUE THREAD

**Issue by SuperSharpBlue** [Gnat008/PerWorldInventory#9]
I seem to be having a problem where exp is not being saved when a player logs off the server. It works just fine when switching worlds.I recieve no errors in the console.

Using PerWorldInventory 1.4.0 with CraftBukkit 1.8.3-R0.1-SNAPSHOT

Here is the config.yml
first-start: false
manage-gamemodes: true
separate-gamemode-inventories: true
player:
  ender-chest: true
  inventory: true
  stats: true
player-stats:
  can-fly: true
  display-name: false
  exhaustion: true
  exp: true
  food: true
  flying: true
  gamemode: true
  health: true
  level: true
  potion-effects: true
  saturation: true

**Comment by Gnat008** [comment]
Thats... odd. Considering i dont load any data when a player logs in. See if you gave any plugins that could be interfering, and i'll also look into it.

**Comment by Gnat008** [comment]
I am unable to reproduce this behaviour on my testing server. What other plugins do you have?

**Comment by SuperSharpBlue** [comment]
I have tried reinstalling your plugin but the problem persists.

List of our plugins:
CommandSigns, WorldEdit, NoMelt, AdvancedMotd, Buycraft, ColoredSigns, Vault, BlockDisguise, PlotMe, PermissionsEx, SkyBlock, WorldGuard, Parkour, iConomy, PerWorldInventory, TNTRun, CoreProtect, SkyWars, ClearLag, FairPvp, ProtocolLib, PlotMe-DefaultGenerator, SuperTrails, AutoAnnouncer, Essentials, SignURLs, NoCheatPlus, LibsDisguises, EssentialsSpawn, Multiverse-Core, LWC, EnjinMinecraftPlugin, Autorank, ChestShop, EssentialsChat, BattleArena, MobArena, Multiverse-Portals, Multiverse-NetherPortals

**Comment by Gnat008** [comment]
Does the issue go away when PerWorldInventories is removed?

**Comment by SuperSharpBlue** [comment]
The issue is still present when the plugin is removed

**Comment by Gnat008** [comment]
Therefore, it cant be an issue with my plugin. One of the others is causing problem.
