### ISSUE TITLE
Problem with gamemode when changing world

### ISSUE THREAD

**Issue by bryanquatremare** [Gnat008/PerWorldInventory#92]
Hi,

I have a problem on my server, when a player, who is in a survival world, go to a creative world, he keep the survival gamemode including admins.
Every player have the permission -perworldinventory.bypass.*

My server is on spigot 1.9.4 with these plugins:
![plugins](https://cloud.githubusercontent.com/assets/17620337/18211429/cf58c81e-713d-11e6-9a6e-327c15c9897d.png)

Here are my config files:
[config.txt](https://github.com/Gnat008/PerWorldInventory/files/452533/config.txt)

[worlds.txt](https://github.com/Gnat008/PerWorldInventory/files/452535/worlds.txt)

**Comment by Gnat008** [comment]
Could you please enable debugging in the plugin config, reproduce the issue, and post your server log?

**Comment by tiploufdu76** [comment]
![image](https://cloud.githubusercontent.com/assets/17620337/18223880/29ffd622-71c5-11e6-9ad6-f54953e29814.png)

**Comment by Gnat008** [comment]
I don't see anything wrong in that snippet. Could you try updating PWI and trying again?

**Comment by tiploufdu76** [comment]
I've updated the plugin to the version 1.8.2 but the problem persists.
