### ISSUE TITLE
Case Sensitive

### ISSUE THREAD

**Issue by angusruler** [Gnat008/PerWorldInventory#95]
Hello!
I figured out that when using the conversion for multiverse inventories, if you are to create the group using in game commands, multiverse inventories can read them without being case sensitive, however, perworldinventories can not, so when converted, PWI doesn't read the worlds that may have been entered differently.

For example, I had a PVP world that was named "PVP" but I typed in "pvp" and multiverse inventories automatically changed it for me, but most likely saved it in the config as the lowercase version since I typed that in. I'm not really sure how it works I'm just assuming.
I noticed that when converted over to PWI, in the config files, it was also lowercase, and did not work because there is no world just called PVP.

This issue is easily fixable by looking around, however, I thought I'd just suggest attempting to fix this, in case anyone else has any problems.
This isn't really a support issue since I already fixed it, but I didn't know where else to put a suggestion, sorry. :c 

I hope this is helpful!

**Comment by Gnat008** [comment]
The worlds.yml configuration file is case sensitive by design.

**Comment by angusruler** [comment]
That's odd, because, after converting from multiverse this is what my worlds.yml looked like

groups:
  default:
    worlds:
    - world
    - world_nether
    - world_the_end
    default-gamemode: SURVIVAL
  __unconfigured__:
    worlds:
    - Survival
    - PVP
    default-gamemode: SURVIVAL
  survival:
    worlds:
    - mgworld
    - survival
    - shops
    default-gamemode: SURVIVAL
  pvp:
    worlds:
    - pvpshops
    - pvp
    default-gamemode: SURVIVAL
  creative:
    worlds:
    - plotworld
    default-gamemode: SURVIVAL

Maybe I'm just missing something dumb, or have an older version or something, I don't know.
