### ISSUE TITLE
Trouble when saving inventories!

### ISSUE THREAD

**Issue by Pixel2Art** [Gnat008/PerWorldInventory#97]
Good day sir!

Your plugin is a must have! It worked really well in 1.8 but when I updated to 1.9.2 things got a bit more complicated! Even when I updated your plugin to 1.8.1 I got that "java.lang.NullPointerException". If you could please fix it, it would be appreciated a lot! Keep up developing those awesome plugins!

Note that I also get that error with your other versions (1.8.0 , 1.7.8 , 1.7.7 ,1.7.6 ,1.7.5 ,1.7.4)
Thank you very much!

If I do something wrong please notify me!

http://pastebin.com/EszKjrtc

Contact me if you want more details!

Thank you again for everything!

**Comment by Pixel2Art** [comment]
Good day sir!

I ran the same version of your plugin (1.8.1) and worked really well on my second server which is (again) in Minecraft 1.9.2 but with different plugins! The plugins that I use for my first server (which I have the error "NullPointerException") are : 

NoFallDamage, TabMessage, NametagEdit, Spawner, ConsoleSpamFix, DKLib, MultiWorld, SkinsRestorer, DeluxeTags, ConsoleSay, NoteBlockAPI, ServerMusic, Actionbar, Backpacks, Titlebar, AsyncWorldEditInjector, WorldEdit, AdminFun, NoRain, Essentials, AutoMessage, SurvivalGames, Chairs, RandomTP, ProtocolLib, LibsDisguises, AdvancedPortals, AsyncWorldEdit, EssentialsChat, PermissionsEx, mcMMO, Vault, ObsidianAuctions, PerWorldInventory, HolographicDisplays, LWC, WorldGuard, SkyWars, CreeperHeal, EssentialsSpawn, MyCommand, AreaShop, CompatNoCheatPlus, ScoreboardStats, ServerlistMOTD, WhatIsIt, NoCheatPlus, VanishNoPacket, HeavySpleef, GriefPrevention, ChestShop, AuthMe, CS-CoreLib, QuickSell

Also, when I change world I get that in my chat: 
Something went horribly wrong when loading your inventory! Please notify a server administrotor!

And in my console:
[PerWorldInventory] Unable to find inventory data for player 'Pixel2Art' for group 'Games': plugins\PerWorldInventory\datadefaults\__default.json (The system cannot find the path specified)

If I do something wrong please let me know!

Thanks in advance! :smile:

**Comment by Gnat008** [comment]
@Pixel2Art Is this still an issue in the latest version?

**Comment by Pixel2Art** [comment]
Hello there!

Yes! With the latest version, it works perfectly fine! Thank you very much! Keep on coding!

**Comment by Pixel2Art** [comment]
Thanks again! Do what ever you want with this issue now.
